---
- include_tasks: start_jenkins.yml
  when: jenkins_service_state == 'started'

- include_tasks: stop_jenkins.yml
  when: jenkins_service_state == 'stopped'

- include_tasks: restart_jenkins.yml
  when: jenkins_service_state == 'restarted'
