- name: "restart_jenkins : get jenkins restart lockfile age."
  shell: "[ -f {{ jenkins_service_restart_lockfile_path }} ] && echo $(($(date +%s%N | cut -b1-13) - $(date +%s%N -r {{ jenkins_service_restart_lockfile_path }} | cut -b1-13 )))"
  register: _jenkins_service_lockfile_age
  failed_when: false
  when: jenkins_service_restart_lockfile_enabled == true

- block:
  - name: "restart_jenkins : include stop tasks."
    include_tasks: stop_jenkins.yml
  - name: "restart_jenkins : include start tasks."
    include_tasks: start_jenkins.yml
  - name: "restart_jenkins : touch jenkins restart lockfile age."
    file:
      path: "{{ jenkins_service_restart_lockfile_path }}"
      state: touch
      mode: 666
    when: jenkins_service_restart_lockfile_enabled == true
  when: (jenkins_service_restart_lockfile_enabled == false) or
        (_jenkins_service_lockfile_age.stdout == "") or
        (_jenkins_service_lockfile_age.stdout|int > jenkins_service_restart_lockfile_age)
